import { staffData } from "@/lib/staff-workspace";
import { asText } from "@/lib/portal";
import { chicagoInput } from "@/lib/staff-policy";
import { saveShift, respondShift } from "../workspace-actions";
import { Workspace, Panel, Field, Save, inputClass } from "../workspace-ui";
export const dynamic = "force-dynamic";
type Row={id:string;fields:Record<string,unknown>};
function ShiftForm({row,roster}:{row?:Row;roster:{id:string;name:string;email:string}[]}) {
 const f=row?.fields||{};
 return <form action={saveShift} className="grid gap-4 md:grid-cols-2"><input type="hidden" name="id" value={row?.id||""}/><Field label="Shift title"><input name="title" required defaultValue={asText(f.Shift)} className={inputClass}/></Field><Field label="Staff member"><select name="person" required defaultValue={roster.find(p=>p.email===f["Staff Email"])?.id||""} className={inputClass}><option value="" disabled>Select staff</option>{roster.map(p=><option key={p.id} value={p.id}>{p.name} ({p.email})</option>)}</select></Field><Field label="Start (Central Time)"><input type="datetime-local" name="start" required defaultValue={chicagoInput(asText(f.Start))} className={inputClass}/></Field><Field label="End (Central Time)"><input type="datetime-local" name="end" required defaultValue={chicagoInput(asText(f.End))} className={inputClass}/></Field><Field label="Location"><input name="location" defaultValue={asText(f.Location)} className={inputClass}/></Field><Field label="Status"><select name="status" defaultValue={asText(f.Status)||"Scheduled"} className={inputClass}><option>Scheduled</option><option>Cancelled</option><option>Completed</option></select></Field><div className="md:col-span-2"><Field label="Shift instructions"><textarea name="notes" defaultValue={asText(f.Notes)} className={inputClass}/></Field></div><Save>{row?"Save shift":"Add shift"}</Save></form>;
}
const format=(value:string)=>new Intl.DateTimeFormat("en-US",{timeZone:"America/Chicago",dateStyle:"medium",timeStyle:"short"}).format(new Date(value));
export default async function StaffSchedule({searchParams}:{searchParams:Promise<{error?:string;saved?:string;view?:string}>}) {
 const query=await searchParams;const data=await staffData("schedule");
 const rows=data.rows.filter(r=>query.view==="all"||Date.parse(asText(r.fields.End))>=Date.now()).sort((a,b)=>Date.parse(asText(a.fields.Start))-Date.parse(asText(b.fields.Start)));
 return <Workspace title="Staff Scheduling" description="View shift assignments and confirm whether you can attend. All times are Central Time. Shelter Managers and Administrators create, edit, and cancel shifts." notice={query}>
 {data.context.manager&&<Panel title="Schedule a staff shift"><p className="text-sm text-muted-foreground">Assignments appear in each staff member’s portal immediately. Contact staff directly about new shifts and changes; this tool does not send email or text notifications. Changes to time, location, or assignee require a new confirmation.</p><ShiftForm roster={data.roster}/></Panel>}
 <Panel title={data.context.manager?"Staff shifts":"My shifts"}><div className="flex gap-5 text-sm text-primary underline"><a href="?">Upcoming shifts</a><a href="?view=all">Include past shifts</a></div>{!rows.length&&<p>No shifts to display.</p>}{rows.map(row=><article key={row.id} className="rounded-2xl border p-5 space-y-4"><div><h3 className="font-bold text-lg">{asText(row.fields.Shift)}</h3><p>{asText(row.fields["Staff Name"])}</p><p className="text-sm">{format(asText(row.fields.Start))} to {format(asText(row.fields.End))} CT</p><p className="text-sm text-muted-foreground">{asText(row.fields.Location)} · {asText(row.fields.Status)}{row.fields.Status==="Scheduled"?` · ${row.fields.Response||"Pending"}`:""}</p></div><p className="whitespace-pre-wrap text-sm">{asText(row.fields.Notes)}</p>{Boolean(row.fields["Staff Notes"])&&<p className="whitespace-pre-wrap text-sm">Staff response notes: {asText(row.fields["Staff Notes"])}</p>}
 {row.fields["Staff Email"]===data.ownEmail&&row.fields.Status==="Scheduled"&&<form action={respondShift} className="space-y-3"><input type="hidden" name="id" value={row.id}/><input type="hidden" name="snapshot" value={JSON.stringify([row.fields.Start,row.fields.End,row.fields.Location||""])}/><Field label="My attendance"><select name="response" required defaultValue={asText(row.fields.Response)==="Pending"?"":asText(row.fields.Response)} className={inputClass}><option value="" disabled>Select response</option><option>Confirmed</option><option>Unable to Attend</option></select></Field><Field label="Note to the manager"><textarea name="notes" defaultValue={asText(row.fields["Staff Notes"])} className={inputClass}/></Field><Save>Save response</Save></form>}
 {data.context.manager&&<details><summary className="cursor-pointer font-semibold text-primary">Edit or cancel shift</summary><div className="mt-4"><ShiftForm row={row} roster={data.roster}/></div></details>}</article>)}</Panel></Workspace>;
}
