import { staffData } from "@/lib/staff-workspace";
import { asText } from "@/lib/portal";
import { safeResource } from "@/lib/staff-policy";
import { saveMaterial, assignTraining, updateTraining } from "../workspace-actions";
import { Workspace, Panel, Field, Save, inputClass } from "../workspace-ui";
export const dynamic = "force-dynamic";
export default async function StaffTraining({searchParams}:{searchParams:Promise<{error?:string;saved?:string}>}) {
  const data=await staffData("training");
  return <Workspace title="Staff Onboarding" description="Read your training materials, complete assigned steps, and ask questions. Shelter Managers and Administrators assign training and verify completion. Reading a guide does not replace supervised training or approval for specialist duties." notice={await searchParams}>
    {data.context.manager&&<Panel title="Assign onboarding training"><p className="text-sm text-muted-foreground">Staff appear here after an Administrator grants an active Staff or Shelter Manager role in Portal Access. Assign each required guide; add your approved policies and role-specific training below.</p><form action={assignTraining} className="grid gap-4 md:grid-cols-2"><Field label="Staff member"><select name="person" required className={inputClass} defaultValue=""><option value="" disabled>Select staff</option>{data.roster.map(p=><option key={p.id} value={p.id}>{p.name} ({p.email})</option>)}</select></Field><Field label="Published training material"><select name="material" required className={inputClass} defaultValue=""><option value="" disabled>Select training</option>{data.materials.filter(m=>m.fields.Status==="Published").map(m=><option key={m.id} value={m.id}>{asText(m.fields.Title)} · v{asText(m.fields.Version)}</option>)}</select></Field><Field label="Due date (optional)"><input type="date" name="due" className={inputClass}/></Field><div className="self-end"><Save>Assign training</Save></div></form></Panel>}
    <Panel title={data.context.manager?"Staff onboarding progress":"My onboarding tasks"}>
      <p className="text-sm text-muted-foreground">{data.rows.filter(r=>r.fields.Status==="Verified").length} of {data.rows.length} assigned tasks verified.</p>
      {!data.rows.length&&<p>No onboarding tasks have been assigned yet.</p>}
      {data.rows.map(row=><article key={row.id} className="rounded-2xl border p-5 space-y-4"><div><h3 className="font-bold">{asText(row.fields.Task)}</h3><p className="text-sm text-muted-foreground">{asText(row.fields["Staff Name"])} · {asText(row.fields.Status)} · Version {asText(row.fields["Material Version"])}{row.fields["Due Date"]?` · Due ${row.fields["Due Date"]}`:""}</p></div><details><summary className="cursor-pointer font-semibold text-primary">Read assigned training</summary><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed">{asText(row.fields["Training Snapshot"])}</p></details>{Boolean(row.fields["Staff Notes"])&&<p className="text-sm whitespace-pre-wrap">Staff notes: {asText(row.fields["Staff Notes"])}</p>}{Boolean(row.fields["Manager Notes"])&&<p className="text-sm whitespace-pre-wrap">Manager feedback: {asText(row.fields["Manager Notes"])}</p>}{Boolean(row.fields["Verified By"])&&<p className="text-xs text-muted-foreground">Verified by {asText(row.fields["Verified By"])} on {asText(row.fields["Verified At"]).slice(0,10)}</p>}
      {row.fields["Staff Email"]===data.ownEmail&&row.fields.Status!=="Verified"&&<form action={updateTraining} className="space-y-3"><input type="hidden" name="id" value={row.id}/><Field label="Questions or completion notes"><textarea name="notes" defaultValue={asText(row.fields["Staff Notes"])} className={inputClass}/></Field><p className="text-xs text-muted-foreground">Mark complete after reading the guide and carrying out its practice steps. A manager will review your completion.</p><Save>Mark completed</Save></form>}
      {data.context.manager&&<form action={updateTraining} className="space-y-3 border-t pt-4"><input type="hidden" name="id" value={row.id}/><input type="hidden" name="mode" value="review"/><Field label="Manager review"><select name="status" className={inputClass} defaultValue={row.fields.Status==="Verified"?"Verified":"Needs Follow-Up"}><option>Verified</option><option>Needs Follow-Up</option><option>Assigned</option></select></Field><Field label="Feedback visible to staff"><textarea name="notes" className={inputClass} defaultValue={asText(row.fields["Manager Notes"])}/></Field><Save>Save review</Save></form>}</article>)}
    </Panel>
    <Panel title="Training materials"><p className="text-sm text-muted-foreground">Portal guides are available below. Safe Haven policies, emergency procedures, and clinical protocols must be supplied and approved by the appropriate manager. Assigned copies retain their original version.</p>{data.materials.map(m=>{let url="";try{url=safeResource(asText(m.fields["Resource URL"]));}catch{} return <details key={m.id} className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">{asText(m.fields.Title)} · v{asText(m.fields.Version)}{data.context.manager?` · ${m.fields.Status}`:""}</summary><p className="mt-4 whitespace-pre-wrap text-sm leading-relaxed">{asText(m.fields.Content)}</p>{url&&<a href={url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-block text-primary underline">Open training resource</a>}{data.context.manager&&<form action={saveMaterial} className="mt-5 space-y-3 border-t pt-4"><input type="hidden" name="id" value={m.id}/><Field label="Title"><input name="title" required defaultValue={asText(m.fields.Title)} className={inputClass}/></Field><Field label="Training instructions"><textarea name="content" rows={8} defaultValue={asText(m.fields.Content)} className={inputClass}/></Field><Field label="Resource URL"><input type="url" name="url" defaultValue={asText(m.fields["Resource URL"])} className={inputClass}/></Field><Field label="Status"><select name="status" defaultValue={asText(m.fields.Status)} className={inputClass}><option>Draft</option><option>Published</option><option>Archived</option></select></Field><Save>Save new version</Save></form>}</details>})}</Panel>
    {data.context.manager&&<Panel title="Add training material"><form action={saveMaterial} className="space-y-4"><Field label="Title"><input name="title" required className={inputClass}/></Field><Field label="Training instructions and practice steps"><textarea name="content" rows={8} className={inputClass}/></Field><Field label="Approved document or video URL (optional)"><input type="url" name="url" className={inputClass}/></Field><Field label="Status"><select name="status" className={inputClass}><option>Draft</option><option>Published</option></select></Field><Save>Add material</Save></form></Panel>}
  </Workspace>;
}
